version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./data/:/usr/wakatime/data

  bot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run bot
    ports:
      - ${BOT_PORT}:${BOT_PORT}
    cap_add:
      - SYS_ADMIN
